# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_maker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_maker.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11robot_maker.proto\x12\x06protos\"4\n\x11\x43ookRecipeRequest\x12\x10\n\x08quantity\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"V\n\x16ListCookRecipeResponse\x12-\n\tresponses\x18\x01 \x03(\x0b\x32\x1a.protos.CookRecipeResponse\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"5\n\x12\x43ookRecipeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2W\n\nRobotMaker\x12I\n\nCookRecipe\x12\x19.protos.CookRecipeRequest\x1a\x1e.protos.ListCookRecipeResponse\"\x00\x62\x06proto3'
)




_COOKRECIPEREQUEST = _descriptor.Descriptor(
  name='CookRecipeRequest',
  full_name='protos.CookRecipeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantity', full_name='protos.CookRecipeRequest.quantity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='protos.CookRecipeRequest.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=81,
)


_LISTCOOKRECIPERESPONSE = _descriptor.Descriptor(
  name='ListCookRecipeResponse',
  full_name='protos.ListCookRecipeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='protos.ListCookRecipeResponse.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='protos.ListCookRecipeResponse.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=169,
)


_COOKRECIPERESPONSE = _descriptor.Descriptor(
  name='CookRecipeResponse',
  full_name='protos.CookRecipeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='protos.CookRecipeResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='protos.CookRecipeResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=224,
)

_LISTCOOKRECIPERESPONSE.fields_by_name['responses'].message_type = _COOKRECIPERESPONSE
DESCRIPTOR.message_types_by_name['CookRecipeRequest'] = _COOKRECIPEREQUEST
DESCRIPTOR.message_types_by_name['ListCookRecipeResponse'] = _LISTCOOKRECIPERESPONSE
DESCRIPTOR.message_types_by_name['CookRecipeResponse'] = _COOKRECIPERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CookRecipeRequest = _reflection.GeneratedProtocolMessageType('CookRecipeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COOKRECIPEREQUEST,
  '__module__' : 'robot_maker_pb2'
  # @@protoc_insertion_point(class_scope:protos.CookRecipeRequest)
  })
_sym_db.RegisterMessage(CookRecipeRequest)

ListCookRecipeResponse = _reflection.GeneratedProtocolMessageType('ListCookRecipeResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTCOOKRECIPERESPONSE,
  '__module__' : 'robot_maker_pb2'
  # @@protoc_insertion_point(class_scope:protos.ListCookRecipeResponse)
  })
_sym_db.RegisterMessage(ListCookRecipeResponse)

CookRecipeResponse = _reflection.GeneratedProtocolMessageType('CookRecipeResponse', (_message.Message,), {
  'DESCRIPTOR' : _COOKRECIPERESPONSE,
  '__module__' : 'robot_maker_pb2'
  # @@protoc_insertion_point(class_scope:protos.CookRecipeResponse)
  })
_sym_db.RegisterMessage(CookRecipeResponse)



_ROBOTMAKER = _descriptor.ServiceDescriptor(
  name='RobotMaker',
  full_name='protos.RobotMaker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=226,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='CookRecipe',
    full_name='protos.RobotMaker.CookRecipe',
    index=0,
    containing_service=None,
    input_type=_COOKRECIPEREQUEST,
    output_type=_LISTCOOKRECIPERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROBOTMAKER)

DESCRIPTOR.services_by_name['RobotMaker'] = _ROBOTMAKER

# @@protoc_insertion_point(module_scope)
