apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jsfranco@whaleandjaguar.co
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-route53
    solvers:
      - selector:
          dnsZones:
            - "sebastianfranco.me"
        dns01:
          route53:
            region: us-west-2
            hostedZoneID: Z05595372RJ37741S3GJD
            role: arn:aws:iam::901305836452:role/botney-eks-cert_manager-irsa
