apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ambassador-certmanager
  # namespace: cert-manager
  namespace: ambassador
spec:
  secretName: ambassador-certmanager
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
  dnsNames:
    - "*.sebastianfranco.me"
