---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildcard-host
  namespace: ambassador
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  tlsSecret:
    name: ambassador-certmanager
  selector:
    matchLabels:
      hostname: wildcard-host
