swagger: '2.0'
info:
    title: Poutine microservice - Chef
    version: '1'
consumes: [application/json]
produces: [application/json]
schemes: [http]
paths:
    /check:
        get:
            tags: [check]
            summary: 'Checks if the server is running'
            responses:
                200:
                    description: 'The server is running'
                    schema:
                        type: object
                        properties:
                            ok:
                                type: boolean
    /poutine:
        get:
            tags: [poutine]
            summary: 'Get the best poutine in town to past 2am drunked people. The chef may sing'
            parameters:
                - name: oil
                  in: query
                  description: 'The oil to use.'
                  type: string
                  enum:
                      - canola
                      - sunflower
                      - colza
            responses:
                200:
                    description: 'A cardbox containing the poutine'
                    schema:
                        type: object
                default:
                    description: Unexpected error
                    schema:
                        $ref: '#/definitions/Error'

definitions:
    Error:
        required:
            - statusCode
            - message
        properties:
            statusCode:
                type: integer
                format: int32
            message:
                type: string
        example:
            statusCode: 404
            message: Page Not Found...
