swagger: "2.0"
info:
  description: "Robot Bizar"
  version: "1.0.0"
  title: "La Poutine Mtl"
  termsOfService: ""
  contact:
    email: "jshn.singh1@gmail.com"
  license:
    name: "MIT OpenSource"
    url: "https://opensource.org/licenses/MIT"
host: "lapoutinemtl.com"
basePath: "/bizar"
paths:
  /fry:
    post:
      tags:
        - "fry potatoes"
      summary: "fry potatoes in the chosen oil"
      description: ""
      operationId: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
