output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.aws_region
}

output "name_servers" {
  description = "AWS DNS servers"
  value       = element(concat(resource.aws_route53_zone.primary[*].name_servers, [""]), 0)
}

output "ingress_hostname_aws" {
  description = "AWS Ingress IP"
  value       = data.kubernetes_service.ambassador_loadbalancer.status.0.load_balancer.0.ingress.0.hostname
}

output "cert_manager_irsa_role_arn" {
  value = module.cert_manager_irsa.iam_role_arn
}