version: '3.3'

services:
    bizar:
        image: 'robot-maker:dev'
        env_file:
            - ./docker.env
        environment:
            - ROBOT_NAME=bizar
            - FRYING_OILS=canola,sunflower,colza

    montroyashi:
        image: 'robot-maker:dev'
        env_file:
            - ./docker.env
        environment:
            - ROBOT_NAME=montroyashi

    nordo:
        image: 'robot-maker:dev'
        env_file:
            - ./docker.env
        environment:
            - ROBOT_NAME=nordo

    oldoporto:
        image: 'robot-maker:dev'
        env_file:
            - ./docker.env
        environment:
            - ROBOT_NAME=oldoporto

    outremona:
        image: 'robot-maker:dev'
        env_file:
            - ./docker.env
        environment:
            - ROBOT_NAME=outremona

    pierre:
        image: 'robot-maker:dev'
        env_file:
            - ./docker.env
        environment:
            - ROBOT_NAME=pierre

    verduny:
        image: 'robot-maker:dev'
        env_file:
            - ./docker.env
        environment:
            - ROBOT_NAME=verduny

    chef:
        image: 'robot-maker:dev'
        env_file:
            - ./docker.env
        environment:
            - ROBOT_NAME=chef

    reverse-proxy:
        image: nginx:1.19.5
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on:
            - bizar
            - montroyashi
            - nordo
            - oldoporto
            - outremona
            - pierre
            - verduny
            - chef
