swagger: "2.0"
info:
  description: "Robot Montroyashi"
  version: "1.0.0"
  title: "La Poutine Mtl"
  termsOfService: ""
  contact:
    email: "mtl.jashanjotsingh@gmail.com"
  license:
    name: "MIT OpenSource"
    url: "https://opensource.org/licenses/MIT"
host: "lapoutinemtl.com"
basePath: "/montroyashi"
paths:
  /drunks/detect:
    get:
      tags:
      - "detect drunks"
      summary: "detect drunk people"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
