swagger: '2.0'
info:
    title: Poutine microservice - Pierre Robot Maker
    version: '1'
consumes: [application/json]
produces: [application/json]
schemes: [http]
paths:
    /check:
        get:
            tags: [check]
            summary: 'Checks if the server is running'
            responses:
                200:
                    description: 'The server is running'
                    schema:
                        type: object
                        properties:
                            ok:
                                type: boolean
    /mix:
        post:
            tags: [poutine]
            summary: 'Mix given object'
            parameters:
                - name: body
                  in: body
                  description: 'The object to mix.'
                  schema:
                      type: object
            responses:
                200:
                    description: 'The mixed object'
                    schema:
                        type: object
                        properties:
                            mixed:
                                type: boolean
                        additionalProperties: true
                400:
                    description: 'There is nothing to mix'
                    schema:
                        $ref: '#/definitions/Error'
                default:
                    description: Unexpected error
                    schema:
                        $ref: '#/definitions/Error'

definitions:
    Error:
        required:
            - statusCode
            - message
        properties:
            statusCode:
                type: integer
                format: int32
            message:
                type: string
        example:
            statusCode: 404
            message: Page Not Found...
