@baseUrl = http://localhost:5001
@urlPath = api/v1/user

###
### @Desc Register a User
POST {{baseUrl}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "secrestssss-carib@hotmail.com",
  "password": "123s4567",
  "avatarImage": "<add-a-base64-encoded-string>"
}

###
### @Desc Login a User
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "",
  "password": ""
}

###
GET {{baseUrl}}/{{urlPath}}/logout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true
