FROM golang:latest

EXPOSE 5000-5010

LABEL maintainer="ssubedir <ssubedir@gmail.com>"

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...
RUN go build -o bizar

CMD ["./bizar"]