version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - '5432:5432'
  backend: 
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - '5050:5050'  
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports: 
      - 3000:3000