services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: caribDB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
     - '5432:5432'
  backend: 
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '5050:5050'  
    volumes:
      - /backdir/node_modules
      - ./backend:/backdir
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/frontdir
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080