swagger: "2.0"
info:
  description: "Robot Verduny"
  version: "1.0.0"
  title: "La Poutine Mtl"
  termsOfService: ""
  contact:
    email: "jshn.singh1@gmail.com"
  license:
    name: "MIT OpenSource"
    url: "https://opensource.org/licenses/MIT"
host: "lapoutinemtl.com"
basePath: "/verduny"
paths:
  /cut:
    post:
      parameters:
        - name: size
          in: query
          type: string
          default: 1
      tags:
        - "cut potatoes"
      summary: "cut potatoes in a dynamically sized cube"
      description: ""
      operationId: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "cut potatoes in given size are returned"
          schema:
            $ref: '#/definitions/Potatoes'
  /dip:
    post:
      tags:
        - "dip potatoes"
      summary: "dip potatoes in maple syrup"
      description: ""
      operationId: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
definitions:
  Potatoes:
    type: object
    properties:
      cutPotatoes:
        $ref: '#/definitions/Potato'
  Potato:
    type: object
    properties:
      cutSize:
        type: string
        default: ""
      portion:
        type: string
        default: ""
      dippedIn:
        type: string
        default: ""
      areCooked:
        type: boolean
        default: false