parser: '@typescript-eslint/parser'
extends: ['plugin:@typescript-eslint/recommended', 'prettier/@typescript-eslint', 'plugin:prettier/recommended']
parserOptions:
    ecmaVersion: 2018
    sourceType: module
plugins: ['import', 'prettier']
rules:
    'import/imports-first': ['error', 'absolute-first']
    'import/newline-after-import': 'error'
    'no-console': 0
    'no-use-before-define': ['error', { 'functions': false, 'classes': true }]
    '@typescript-eslint/no-use-before-define': ['error', { 'functions': false, 'classes': true }]
    '@typescript-eslint/no-explicit-any': 0
    '@typescript-eslint/explicit-function-return-type': ['error', { 'allowExpressions': true }]
env:
    jest: true
