version: '3.3'

services:
    nordo:
        image: 'robot-maker:dev'
        env_file:
            - ./.env
        environment:
            - ROBOT_NAME=nordo
    outremona:
        image: 'robot-maker:dev'
        env_file:
            - ./.env
        environment:
            - ROBOT_NAME=outremona

    reverse-proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
