version: "3.8"
services:
  pubsub:
    image: redis
    container_name: pubsub
    expose:
      - 6379
  pierre:
    build: ./cmd/pierre/
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=pubsub:6379
      - HTTP_HOST=:8080
    links:
      - pubsub
  outremona:
    build: ./cmd/outremona/
    ports:
      - 8081:8081
    environment:
      - REDIS_HOST=pubsub:6379
      - HTTP_HOST=:8081
    links:
      - pubsub
  montroyashi:
    build: ./cmd/montroyashi/
    ports:
      - 8082:8082
    environment:
      - REDIS_HOST=pubsub:6379
      - HTTP_HOST=:8082
    links:
      - pubsub
  verduny:
    build: ./cmd/verduny/
    ports:
      - 8083:8083
    environment:
      - REDIS_HOST=pubsub:6379
      - HTTP_HOST=:8083
    links:
      - pubsub
  nordo:
    build: ./cmd/nordo/
    ports:
      - 8084:8084
    environment:
      - REDIS_HOST=pubsub:6379
      - HTTP_HOST=:8084
    links:
      - pubsub
  bizar:
    build: ./cmd/bizar/
    ports:
      - 8085:8085
    environment:
      - REDIS_HOST=pubsub:6379
      - HTTP_HOST=:8085
    links:
      - pubsub
  oldoporto:
    build: ./cmd/oldoporto/
    ports:
      - 8086:8086
    environment:
      - REDIS_HOST=pubsub:6379
      - HTTP_HOST=:8086
    links:
      - pubsub
