version: '3.3'

services:
    nordo:
        image: "robot-maker:dev"
        ports:
          - "8080:8080"
        env_file:
          - ./.env
        environment:
          - ROBOT_NAME=nordo
    outremona:
        image: "robot-maker:dev"
        ports:
          - "8081:8080"
        env_file:
          - ./.env
        environment:
          - ROBOT_NAME=outremona
