.PHONY: run nordo outremona verduny bizarg bizar oldoporto pierre orderservice

run:
	docker-compose up
nordo:
	docker build -t nordo ./nordo
outremona:
	docker build -t outremona ./outremona
verduny:
	docker build -t verduny ./verduny
bizarg:
	docker build -t bizargateway ./bizar
bizar:
	docker build -t bizar-oil ./bizar/bizaroil
oldoporto:
	docker build -t oldoporto ./oldoporto
pierre:
	docker build -t pierre ./pierre
orderservice:
	docker build -t orderservice .