# Generated by Django 2.2.5 on 2020-12-30 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Customer id')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comment')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Rate')),
                ('like', models.IntegerField(blank=True, null=True, verbose_name='Likes')),
                ('dislike', models.IntegerField(blank=True, null=True, verbose_name='Dislikes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'db_table': 'Comments',
                'ordering': ['comment_id'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Customer id')),
                ('customer_type', models.IntegerField(blank=True, default=0, null=True, verbose_name='Customer type')),
                ('drink_preferences', models.IntegerField(blank=True, default=0, null=True, verbose_name='Drink preferences')),
                ('food_preferences', models.IntegerField(blank=True, default=0, null=True, verbose_name='Food preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'Customers',
                'ordering': ['customer_id'],
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order id')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Last order date')),
                ('conservation', models.IntegerField(blank=True, default=0, null=True, verbose_name='Conservation (min)')),
                ('available', models.BooleanField(blank=True, null=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'db_table': 'Menus',
                'ordering': ['menu_id'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order id')),
                ('customers', models.IntegerField(blank=True, null=True, verbose_name='Number of customer')),
                ('split_bill', models.IntegerField(blank=True, null=True, verbose_name='Split bill')),
                ('delivered', models.BooleanField(blank=True, default=False, null=True, verbose_name='Delivered')),
                ('paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'Orders',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('table_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table id')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Number of customer')),
                ('available', models.BooleanField(verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name_plural': 'Tables',
                'db_table': 'Tables',
                'ordering': ['table_id'],
            },
        ),
        migrations.CreateModel(
            name='Orders_Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('cooking', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cooking')),
                ('tone', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tone')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Menus')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Orders')),
            ],
            options={
                'db_table': 'Orders_Menus',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Tables'),
        ),
        migrations.AddField(
            model_name='menus',
            name='orders',
            field=models.ManyToManyField(related_name='OrdersMenus', through='cafe.Orders_Menus', to='cafe.Orders'),
        ),
        migrations.CreateModel(
            name='HistoricalTables',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('table_id', models.IntegerField(blank=True, db_index=True, verbose_name='Table id')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Number of customer')),
                ('available', models.BooleanField(verbose_name='Available')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tables',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrders_Menus',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('cooking', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cooking')),
                ('tone', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tone')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cafe.Menus')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cafe.Orders')),
            ],
            options={
                'verbose_name': 'historical orders_ menus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrders',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('order_id', models.IntegerField(blank=True, db_index=True, verbose_name='Order id')),
                ('customers', models.IntegerField(blank=True, null=True, verbose_name='Number of customer')),
                ('split_bill', models.IntegerField(blank=True, null=True, verbose_name='Split bill')),
                ('delivered', models.BooleanField(blank=True, default=False, null=True, verbose_name='Delivered')),
                ('paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cafe.Tables')),
            ],
            options={
                'verbose_name': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMenus',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('menu_id', models.IntegerField(blank=True, db_index=True, verbose_name='Order id')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Last order date')),
                ('conservation', models.IntegerField(blank=True, default=0, null=True, verbose_name='Conservation (min)')),
                ('available', models.BooleanField(blank=True, null=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical menus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomers_Orders_Comments',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cafe.Comments')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cafe.Customers')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cafe.Orders')),
            ],
            options={
                'verbose_name': 'historical customers_ orders_ comments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomers',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('customer_id', models.IntegerField(blank=True, db_index=True, verbose_name='Customer id')),
                ('customer_type', models.IntegerField(blank=True, default=0, null=True, verbose_name='Customer type')),
                ('drink_preferences', models.IntegerField(blank=True, default=0, null=True, verbose_name='Drink preferences')),
                ('food_preferences', models.IntegerField(blank=True, default=0, null=True, verbose_name='Food preferences')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical customers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComments',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('comment_id', models.IntegerField(blank=True, db_index=True, verbose_name='Customer id')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comment')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Rate')),
                ('like', models.IntegerField(blank=True, null=True, verbose_name='Likes')),
                ('dislike', models.IntegerField(blank=True, null=True, verbose_name='Dislikes')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Customers_Orders_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.Comments')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Customers')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Orders')),
            ],
            options={
                'db_table': 'Customers_Orders_Comments',
            },
        ),
    ]
