apiVersion: v1
kind: Namespace
metadata:
  labels:
    author: jhonsfran
    env: development
  name: development
---
apiVersion: v1
data:
  CLOUD: ImRpZ2l0YWxvY2VhbiI=
  ENV: ImRldmVsb3BtZW50Ig==
kind: Secret
metadata:
  labels:
    author: jhonsfran
    env: development
  name: botney-env-k59t9f8f6d
  namespace: development
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    author: jhonsfran
    env: development
  name: botney-trap
  namespace: development
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: botney-trap
    author: jhonsfran
    env: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: botney-trap
    author: jhonsfran
    env: development
  name: botney-trap
  namespace: development
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: botney-trap
      author: jhonsfran
      env: development
  template:
    metadata:
      labels:
        app: botney-trap
        author: jhonsfran
        env: development
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: botney-env-k59t9f8f6d
        image: jhonsfran/botney-trap:latest
        imagePullPolicy: Always
        name: botney-trap
        ports:
        - containerPort: 3000
          name: http
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    author: jhonsfran
    env: development
  name: botney-trap
  namespace: development
spec:
  host: dev.sebastianfranco.me
  idle_timeout_ms: 55000000
  prefix: /
  service: botney-trap
  timeout_ms: 55000000
