apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/app
  - deployment.yaml
  - service.yaml

namespace: development
commonLabels:
  author: jhonsfran
  env: development

# TODO: encrypting secrets
secretGenerator:
  - envs:
      - botney.env
    name: botney-env

# TODO: versioning images - apply gitops
images:
  - name: jhonsfran/botney-trap
    newName: jhonsfran/botney-trap
    newTag: latest
