# Generated by Django 2.2.5 on 2020-12-30 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('thesaurus_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150, verbose_name='Label')),
            ],
            options={
                'verbose_name_plural': 'Thesaurus',
                'db_table': 'Thesaurus',
                'ordering': ['thesaurus_id'],
            },
        ),
        migrations.CreateModel(
            name='ThesaurusOption',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('Thesaurus_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('thesaurus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='parameters.Thesaurus', verbose_name='Thesaurus')),
            ],
            options={
                'verbose_name': 'ThesaurusOptions',
                'db_table': 'ThesaurusOption',
                'ordering': ['Thesaurus_option_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalThesaurusOption',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('Thesaurus_option_id', models.IntegerField(blank=True, db_index=True)),
                ('code', models.IntegerField(verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thesaurus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parameters.Thesaurus', verbose_name='Thesaurus')),
            ],
            options={
                'verbose_name': 'historical ThesaurusOptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalThesaurus',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('thesaurus_id', models.IntegerField(blank=True, db_index=True)),
                ('label', models.CharField(max_length=150, verbose_name='Label')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical thesaurus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
