
const customers = [
		{
			"id": 1,
			"first_name": "Maggi",
			"last_name": "Domney",
			"email": "mdomney0@wisdompets.com",
			"address": "53177 Fieldstone Pass",
			"city": "San Bernardino",
			"State": "CA",
			"phone_number": "760-702-5469",
			"Birthday": "1938-10-11",
			"favorite_dish": 15
		},
		{
			"id": 2,
			"first_name": "Javier",
			"last_name": "Dawks",
			"email": "jdawks1@red30design.com",
			"address": "25629 Brown Trail",
			"city": "Hartford",
			"State": "CT",
			"phone_number": "860-906-1459",
			"Birthday": "1953-11-21",
			"favorite_dish": 13
		},
		{
			"id": 3,
			"first_name": "Aleen",
			"last_name": "Fasey",
			"email": "afasey2@kinetecoinc.com",
			"address": "41967 Mockingbird Court",
			"city": "Boca Raton",
			"State": "FL",
			"phone_number": "561-410-2222",
			"Birthday": "1900-08-10",
			"favorite_dish": 3
		},
		{
			"id": 4,
			"first_name": "Taylor",
			"last_name": "Jenkins",
			"email": "tjenkins@rouxacademy.org",
			"address": "968 Bartillon Park",
			"city": "Fort Lauderdale",
			"State": "FL",
			"phone_number": "954-294-7424",
			"Birthday": "1961-05-02",
			"favorite_dish": 8
		},
		{
			"id": 5,
			"first_name": "Imogen",
			"last_name": "Kabsch",
			"email": "ikabsch@landonhotel.com",
			"address": "222 Hudson Point",
			"city": "Anderson",
			"State": "SC",
			"phone_number": "864-326-7456",
			"Birthday": "1919-08-27",
			"favorite_dish": 17
		},
		{
			"id": 6,
			"first_name": "Dunc",
			"last_name": "Winny",
			"email": "dwinny5@kinetecoinc.com",
			"address": "6 Derek Avenue",
			"city": "Columbus",
			"State": "GA",
			"phone_number": "706-389-4923",
			"Birthday": "1919-07-19",
			"favorite_dish": 11
		},
		{
			"id": 7,
			"first_name": "Cammi",
			"last_name": "Kynett",
			"email": "ckynett6@orangevalleycaa.org",
			"address": "237 Homewood Hill",
			"city": "Washington",
			"State": "DC",
			"phone_number": "202-798-6252",
			"Birthday": "1927-03-06",
			"favorite_dish": 5
		},
		{
			"id": 8,
			"first_name": "Steffie",
			"last_name": "Kleis",
			"email": "skleis7@wisdompets.com",
			"address": "360 Little Fleur Park",
			"city": "Evansville",
			"State": "IN",
			"phone_number": "812-301-6915",
			"Birthday": "1957-12-27",
			"favorite_dish": 8
		},
		{
			"id": 9,
			"first_name": "Carilyn",
			"last_name": "Calver",
			"email": "ccalver8@samoca.org",
			"address": "3664 Emmet Circle",
			"city": "Dulles",
			"State": "VA",
			"phone_number": "571-718-5931",
			"Birthday": "1960-12-17",
			"favorite_dish": 12
		},
		{
			"id": 10,
			"first_name": "Barbara-anne",
			"last_name": "Sweet",
			"email": "bsweet9@samoca.org",
			"address": "257 Mallory Drive",
			"city": "San Antonio",
			"State": "TX",
			"phone_number": "210-776-2859",
			"Birthday": "1911-04-01",
			"favorite_dish": 5
		},
		{
			"id": 11,
			"first_name": "Faina",
			"last_name": "Nelles",
			"email": "fnellesa@red30design.com",
			"address": "1143 Nevada Plaza",
			"city": "Reading",
			"State": "PA",
			"phone_number": "484-145-8882",
			"Birthday": "1967-03-06",
			"favorite_dish": 10
		},
		{
			"id": 12,
			"first_name": "Orton",
			"last_name": "Stavers",
			"email": "ostaversb@orangevalleycaa.org",
			"address": "5 Pankratz Junction",
			"city": "Vienna",
			"State": "VA",
			"phone_number": "571-414-2322",
			"Birthday": "1910-07-20",
			"favorite_dish": 22
		},
		{
			"id": 13,
			"first_name": "Jobina",
			"last_name": "McKern",
			"email": "jmckernc@rouxacademy.org",
			"address": "28 Dovetail Circle",
			"city": "San Mateo",
			"State": "CA",
			"phone_number": "805-540-9168",
			"Birthday": "1923-01-19",
			"favorite_dish": 9
		},
		{
			"id": 14,
			"first_name": "Paco",
			"last_name": "Yarranton",
			"email": "pyarrantond@rouxacademy.org",
			"address": "1 Lighthouse Bay Hill",
			"city": "Columbus",
			"State": "OH",
			"phone_number": "614-173-1770",
			"Birthday": "1977-05-08",
			"favorite_dish": 2
		},
		{
			"id": 15,
			"first_name": "Chance",
			"last_name": "Todeo",
			"email": "ctodeoe@wisdompets.com",
			"address": "2 Debra Trail",
			"city": "Dallas",
			"State": "TX",
			"phone_number": "214-351-1058",
			"Birthday": "1924-08-13",
			"favorite_dish": 16
		},
		{
			"id": 16,
			"first_name": "Carla",
			"last_name": "Swinfen",
			"email": "cswinfenf@kinetecoinc.com",
			"address": "949 Northview Junction",
			"city": "South Bend",
			"State": "IN",
			"phone_number": "574-883-7972",
			"Birthday": "1989-05-24",
			"favorite_dish": 10
		},
		{
			"id": 17,
			"first_name": "Lani",
			"last_name": "Over",
			"email": "loverg@wisdompets.com",
			"address": "8 Roxbury Point",
			"city": "Colorado Springs",
			"State": "CO",
			"phone_number": "719-792-4724",
			"Birthday": "1938-08-02",
			"favorite_dish": 20
		},
		{
			"id": 18,
			"first_name": "Anthe",
			"last_name": "Dinjes",
			"email": "adinjesh@samoca.org",
			"address": "4 American Road",
			"city": "Washington",
			"State": "DC",
			"phone_number": "202-164-5786",
			"Birthday": "1903-12-29",
			"favorite_dish": 3
		},
		{
			"id": 19,
			"first_name": "Amby",
			"last_name": "Harber",
			"email": "aharberi@hplussport.com",
			"address": "2985 Pearson Circle",
			"city": "Durham",
			"State": "NC",
			"phone_number": "919-557-3321",
			"Birthday": "1925-06-21",
			"favorite_dish": 9
		},
		{
			"id": 20,
			"first_name": "Jacinta",
			"last_name": "Vallis",
			"email": "jvallisj@kinetecoinc.com",
			"address": "9 Anzinger Lane",
			"city": "Bakersfield",
			"State": "CA",
			"phone_number": "661-103-5365",
			"Birthday": "1994-12-10",
			"favorite_dish": 10
		},
		{
			"id": 21,
			"first_name": "Henri",
			"last_name": "Pughe",
			"email": "hpughek@orangevalleycaa.org",
			"address": "53 Blue Bill Park Point",
			"city": "Manassas",
			"State": "VA",
			"phone_number": "434-339-5926",
			"Birthday": "1955-01-12",
			"favorite_dish": 22
		},
		{
			"id": 22,
			"first_name": "Cassandre",
			"last_name": "Wragg",
			"email": "cwraggl@landonhotel.com",
			"address": "92285 Cascade Center",
			"city": "Washington",
			"State": "DC",
			"phone_number": "703-646-1738",
			"Birthday": "1960-05-01",
			"favorite_dish": 20
		},
		{
			"id": 23,
			"first_name": "Amory",
			"last_name": "Bunyard",
			"email": "abunyardm@samoca.org",
			"address": "9951 Buena Vista Point",
			"city": "Topeka",
			"State": "KS",
			"phone_number": "785-691-3913",
			"Birthday": "1919-01-15",
			"favorite_dish": 14
		},
		{
			"id": 24,
			"first_name": "Carny",
			"last_name": "Scamp",
			"email": "cscampn@wisdompets.com",
			"address": "9 Valley Edge Road",
			"city": "New York city",
			"State": "NY",
			"phone_number": "212-198-3815",
			"Birthday": "1911-02-01",
			"favorite_dish": 14
		},
		{
			"id": 25,
			"first_name": "Paulie",
			"last_name": "Kinvig",
			"email": "pkinvigo@hplussport.com",
			"address": "564 Ryan Park",
			"city": "Philadelphia",
			"State": "PA",
			"phone_number": "215-647-3796",
			"Birthday": "1958-08-12",
			"favorite_dish": 10
		},
		{
			"id": 26,
			"first_name": "Taylor",
			"last_name": "Jenkins",
			"email": "tjenkins@redt30design.com",
			"address": "27170 6th Center",
			"city": "Washington",
			"State": "DC",
			"phone_number": "202-765-8011",
			"Birthday": "1922-05-05",
			"favorite_dish": 12
		},
		{
			"id": 27,
			"first_name": "Yves",
			"last_name": "Dell'Abbate",
			"email": "ydellabbateq@rouxacademy.org",
			"address": "68966 High Crossing Junction",
			"city": "Richmond",
			"State": "VA",
			"phone_number": "804-689-9010",
			"Birthday": "1902-12-23",
			"favorite_dish": 8
		},
		{
			"id": 28,
			"first_name": "Culley",
			"last_name": "Cawood",
			"email": "ccawoodr@samoca.org",
			"address": "536 Darwin Trail",
			"city": "Washington",
			"State": "DC",
			"phone_number": "202-959-7069",
			"Birthday": "1933-03-05",
			"favorite_dish": 12
		},
		{
			"id": 29,
			"first_name": "Herby",
			"last_name": "Aspinal",
			"email": "haspinals@red30design.com",
			"address": "7 Maple Center",
			"city": "Sacramento",
			"State": "CA",
			"phone_number": "916-942-8188",
			"Birthday": "1934-03-28",
			"favorite_dish": 2
		},
		{
			"id": 30,
			"first_name": "Emlyn",
			"last_name": "Attwool",
			"email": "eattwoolt@hplussport.com",
			"address": "289 Westridge Pass",
			"city": "Des Moines",
			"State": "IA",
			"phone_number": "515-478-3690",
			"Birthday": "1976-08-12",
			"favorite_dish": 4
		},
		{
			"id": 31,
			"first_name": "Osgood",
			"last_name": "Saunter",
			"email": "osaunteru@red30design.com",
			"address": "9686 Havey Crossing",
			"city": "Oklahoma city",
			"State": "OK",
			"phone_number": "405-620-8345",
			"Birthday": "1954-12-18",
			"favorite_dish": 14
		},
		{
			"id": 32,
			"first_name": "Demetri",
			"last_name": "Iacobacci",
			"email": "diacobacciv@landonhotel.com",
			"address": "1727 Vermont Point",
			"city": "Newark",
			"State": "DE",
			"phone_number": "302-843-4915",
			"Birthday": "1948-05-05",
			"favorite_dish": 5
		},
		{
			"id": 33,
			"first_name": "Eloisa",
			"last_name": "Forster",
			"email": "eforsterw@wisdompets.com",
			"address": "45084 Butterfield Point",
			"city": "Kalamazoo",
			"State": "MI",
			"phone_number": "269-400-8205",
			"Birthday": "1928-06-22",
			"favorite_dish": 10
		},
		{
			"id": 34,
			"first_name": "Carlin",
			"last_name": "Casterou",
			"email": "ccasteroux@landonhotel.com",
			"address": "17 Cordelia Trail",
			"city": "El Paso",
			"State": "TX",
			"phone_number": "915-815-0411",
			"Birthday": "1940-06-10",
			"favorite_dish": 4
		},
		{
			"id": 35,
			"first_name": "Luciano",
			"last_name": "Winton",
			"email": "lwintony@hplussport.com",
			"address": "386 Fairview Lane",
			"city": "Greensboro",
			"State": "NC",
			"phone_number": "336-968-8032",
			"Birthday": "1951-04-16",
			"favorite_dish": 4
		},
		{
			"id": 36,
			"first_name": "Allyson",
			"last_name": "Jira",
			"email": "ajiraz@wisdompets.com",
			"address": "51474 Northridge Pass",
			"city": "Syracuse",
			"State": "NY",
			"phone_number": "315-720-5302",
			"Birthday": "1996-01-23",
			"favorite_dish": 20
		},
		{
			"id": 37,
			"first_name": "Jillane",
			"last_name": "Livingstone",
			"email": "jlivingstone10@wisdompets.com",
			"address": "4 Arizona Hill",
			"city": "Fairfax",
			"State": "VA",
			"phone_number": "571-135-9052",
			"Birthday": "1928-09-30",
			"favorite_dish": 1
		},
		{
			"id": 38,
			"first_name": "Christyna",
			"last_name": "McGilroy",
			"email": "cmcgilroy11@landonhotel.com",
			"address": "47989 East Court",
			"city": "Washington",
			"State": "DC",
			"phone_number": "202-132-1057",
			"Birthday": "1974-08-01",
			"favorite_dish": 18
		},
		{
			"id": 39,
			"first_name": "Oralla",
			"last_name": "Dayer",
			"email": "odayer12@samoca.org",
			"address": "478 Sommers Pass",
			"city": "Sacramento",
			"State": "CA",
			"phone_number": "916-274-8584",
			"Birthday": "1977-05-27",
			"favorite_dish": 2
		},
		{
			"id": 40,
			"first_name": "Angelique",
			"last_name": "Farnham",
			"email": "afarnham13@wisdompets.com",
			"address": "564 Ohio Crossing",
			"city": "Fort Smith",
			"State": "AR",
			"phone_number": "479-118-1613",
			"Birthday": "1929-06-02",
			"favorite_dish": 20
		},
		{
			"id": 41,
			"first_name": "Lowrance",
			"last_name": "Gratton",
			"email": "lgratton14@hplussport.com",
			"address": "675 Warner Street",
			"city": "New York city",
			"State": "NY",
			"phone_number": "212-562-3242",
			"Birthday": "1946-10-13",
			"favorite_dish": 15
		},
		{
			"id": 42,
			"first_name": "Cleo",
			"last_name": "Goldwater",
			"email": "cgoldwater15@landonhotel.com",
			"address": "9831 Evergreen Way",
			"city": "Tyler",
			"State": "TX",
			"phone_number": "903-791-7266",
			"Birthday": "1959-09-14",
			"favorite_dish": 14
		},
		{
			"id": 43,
			"first_name": "Menard",
			"last_name": "Pitone",
			"email": "mpitone16@red30design.com",
			"address": "8 Petterle Road",
			"city": "Boston",
			"State": "MA",
			"phone_number": "318-237-8464",
			"Birthday": "1948-01-06",
			"favorite_dish": 3
		},
		{
			"id": 44,
			"first_name": "Davy",
			"last_name": "Neely",
			"email": "dneely17@hplussport.com",
			"address": "1 Shelley Road",
			"city": "Orlando",
			"State": "FL",
			"phone_number": "407-752-8159",
			"Birthday": "1942-10-31",
			"favorite_dish": 1
		},
		{
			"id": 45,
			"first_name": "Zechariah",
			"last_name": "Deniske",
			"email": "zdeniske18@kinetecoinc.com",
			"address": "78 Hayes Lane",
			"city": "Gadsden",
			"State": "AL",
			"phone_number": "256-909-6656",
			"Birthday": "1978-07-17",
			"favorite_dish": 21
		},
		{
			"id": 46,
			"first_name": "Serge",
			"last_name": "Pethrick",
			"email": "spethrick19@rouxacademy.org",
			"address": "65 Sunbrook Crossing",
			"city": "New Castle",
			"State": "PA",
			"phone_number": "724-424-9472",
			"Birthday": "1965-12-31",
			"favorite_dish": 1
		},
		{
			"id": 47,
			"first_name": "Lydie",
			"last_name": "Awmack",
			"email": "lawmack1a@samoca.org",
			"address": "454 Prairie Rose Street",
			"city": "Springfield",
			"State": "VA",
			"phone_number": "571-709-9837",
			"Birthday": "1964-03-31",
			"favorite_dish": 8
		},
		{
			"id": 48,
			"first_name": "Clementia",
			"last_name": "Furminger",
			"email": "cfurminger1b@kinetecoinc.com",
			"address": "78 Longview Avenue",
			"city": "El Paso",
			"State": "TX",
			"phone_number": "915-622-4479",
			"Birthday": "1966-03-17",
			"favorite_dish": 4
		},
		{
			"id": 49,
			"first_name": "Cathryn",
			"last_name": "Beau",
			"email": "cbeau1c@wisdompets.com",
			"address": "8860 Lien Road",
			"city": "Reno",
			"State": "NV",
			"phone_number": "775-437-9114",
			"Birthday": "1986-09-02",
			"favorite_dish": 8
		},
		{
			"id": 50,
			"first_name": "Jack",
			"last_name": "Vaan",
			"email": "jvaan1d@wisdompets.com",
			"address": "75 Gateway Circle",
			"city": "Boise",
			"State": "ID",
			"phone_number": "208-648-3163",
			"Birthday": "1949-07-25",
			"favorite_dish": 15
		},
		{
			"id": 51,
			"first_name": "Romeo",
			"last_name": "Annett",
			"email": "rannett1e@samoca.org",
			"address": "9229 Harbort Point",
			"city": "New York city",
			"State": "NY",
			"phone_number": "212-548-7727",
			"Birthday": "1937-11-20",
			"favorite_dish": 8
		},
		{
			"id": 52,
			"first_name": "Arlen",
			"last_name": "O'Fihillie",
			"email": "aofihillie1f@wisdompets.com",
			"address": "20 Bartelt Circle",
			"city": "El Paso",
			"State": "TX",
			"phone_number": "915-295-2257",
			"Birthday": "1906-08-30",
			"favorite_dish": 12
		},
		{
			"id": 53,
			"first_name": "Perceval",
			"last_name": "Redpath",
			"email": "predpath1g@rouxacademy.org",
			"address": "98 Messerschmidt Court",
			"city": "Hyattsville",
			"State": "MD",
			"phone_number": "301-713-2688",
			"Birthday": "1955-12-03",
			"favorite_dish": 1
		},
		{
			"id": 54,
			"first_name": "Ive",
			"last_name": "Iles",
			"email": "iiles1h@samoca.org",
			"address": "75922 Fieldstone Terrace",
			"city": "San Francisco",
			"State": "CA",
			"phone_number": "415-544-7619",
			"Birthday": "1972-10-13",
			"favorite_dish": 22
		},
		{
			"id": 55,
			"first_name": "Robbert",
			"last_name": "Walkowski",
			"email": "rwalkowski1i@kinetecoinc.com",
			"address": "43 Fair Oaks Crossing",
			"city": "Los Angeles",
			"State": "CA",
			"phone_number": "626-967-1974",
			"Birthday": "1996-03-19",
			"favorite_dish": 8
		},
		{
			"id": 56,
			"first_name": "Hagen",
			"last_name": "Itzhayek",
			"email": "hitzhayek1j@landonhotel.com",
			"address": "32205 Drewry Plaza",
			"city": "San Francisco",
			"State": "CA",
			"phone_number": "415-340-3585",
			"Birthday": "1932-10-10",
			"favorite_dish": 6
		},
		{
			"id": 57,
			"first_name": "Kahaleel",
			"last_name": "Keaton",
			"email": "kkeaton1k@kinetecoinc.com",
			"address": "88256 Roxbury Pass",
			"city": "Long Beach",
			"State": "CA",
			"phone_number": "562-637-8856",
			"Birthday": "1989-08-25",
			"favorite_dish": 2
		},
		{
			"id": 58,
			"first_name": "Purcell",
			"last_name": "Llop",
			"email": "pllop1l@hplussport.com",
			"address": "8630 Loeprich Plaza",
			"city": "Clearwater",
			"State": "FL",
			"phone_number": "727-959-7623",
			"Birthday": "1950-05-15",
			"favorite_dish": 3
		},
		{
			"id": 59,
			"first_name": "Cornelia",
			"last_name": "Koppe",
			"email": "ckoppe1m@landonhotel.com",
			"address": "30278 Little Fleur Terrace",
			"city": "Vero Beach",
			"State": "FL",
			"phone_number": "772-132-3079",
			"Birthday": "1972-09-30",
			"favorite_dish": 8
		},
		{
			"id": 60,
			"first_name": "Olympia",
			"last_name": "Sansun",
			"email": "osansun1n@wisdompets.com",
			"address": "76 Ruskin Street",
			"city": "Brooklyn",
			"State": "NY",
			"phone_number": "212-188-0416",
			"Birthday": "1995-01-16",
			"favorite_dish": 14
		},
		{
			"id": 61,
			"first_name": "Rubia",
			"last_name": "Fitzsymon",
			"email": "rfitzsymon1o@red30design.com",
			"address": "79 Rieder Avenue",
			"city": "Tampa",
			"State": "FL",
			"phone_number": "813-121-0276",
			"Birthday": "1982-08-30",
			"favorite_dish": 8
		},
		{
			"id": 62,
			"first_name": "Tybie",
			"last_name": "Balme",
			"email": "tbalme1p@orangevalleycaa.org",
			"address": "17 Pine View Court",
			"city": "Johnson city",
			"State": "TN",
			"phone_number": "423-364-2730",
			"Birthday": "1907-01-21",
			"favorite_dish": 5
		},
		{
			"id": 63,
			"first_name": "Forest",
			"last_name": "Dubock",
			"email": "fdubock1q@red30design.com",
			"address": "3418 Maryland Circle",
			"city": "Tulsa",
			"State": "OK",
			"phone_number": "918-881-4322",
			"Birthday": "1991-10-05",
			"favorite_dish": 4
		},
		{
			"id": 64,
			"first_name": "Norby",
			"last_name": "Sleight",
			"email": "nsleight1r@kinetecoinc.com",
			"address": "16198 Welch Place",
			"city": "Oklahoma city",
			"State": "OK",
			"phone_number": "405-786-8722",
			"Birthday": "1955-11-13",
			"favorite_dish": 7
		},
		{
			"id": 65,
			"first_name": "Hayyim",
			"last_name": "Rossander",
			"email": "hrossander1s@wisdompets.com",
			"address": "5 American Ash Court",
			"city": "Long Beach",
			"State": "CA",
			"phone_number": "323-318-8768",
			"Birthday": "1914-11-08",
			"favorite_dish": 22
		},
		{
			"id": 66,
			"first_name": "Gilbert",
			"last_name": "Dupoy",
			"email": "gdupoy1t@rouxacademy.org",
			"address": "90863 Hermina Center",
			"city": "Toledo",
			"State": "OH",
			"phone_number": "419-487-3597",
			"Birthday": "1997-09-27",
			"favorite_dish": 21
		},
		{
			"id": 67,
			"first_name": "Whitney",
			"last_name": "Lamberts",
			"email": "wlamberts1u@red30design.com",
			"address": "23 Fairview Lane",
			"city": "San Diego",
			"State": "CA",
			"phone_number": "858-417-9425",
			"Birthday": "1996-06-15",
			"favorite_dish": 14
		},
		{
			"id": 68,
			"first_name": "Anastasie",
			"last_name": "Ferguson",
			"email": "aferguson1v@landonhotel.com",
			"address": "28138 Kenwood Park",
			"city": "Salt Lake city",
			"State": "UT",
			"phone_number": "801-920-5569",
			"Birthday": "1930-10-12",
			"favorite_dish": 1
		},
		{
			"id": 69,
			"first_name": "Alaster",
			"last_name": "Ruggles",
			"email": "aruggles1w@red30design.com",
			"address": "661 Grover Center",
			"city": "Saint Paul",
			"State": "MN",
			"phone_number": "651-761-7780",
			"Birthday": "1990-06-25",
			"favorite_dish": 15
		},
		{
			"id": 70,
			"first_name": "Loretta",
			"last_name": "Hundey",
			"email": "lhundey1x@kinetecoinc.com",
			"address": "6939 Elka Place",
			"city": "Los Angeles",
			"State": "CA",
			"phone_number": "310-730-8619",
			"Birthday": "1945-08-14",
			"favorite_dish": 18
		},
		{
			"id": 71,
			"first_name": "Winnah",
			"last_name": "D'Elia",
			"email": "wdelia1y@red30design.com",
			"address": "489 Almo Drive",
			"city": "Whittier",
			"State": "CA",
			"phone_number": "626-579-3814",
			"Birthday": "1965-06-07",
			"favorite_dish": 10
		},
		{
			"id": 72,
			"first_name": "Trip",
			"last_name": "Pond",
			"email": "tpond1z@wisdompets.com",
			"address": "653 Manley Alley",
			"city": "San Jose",
			"State": "CA",
			"phone_number": "408-716-4969",
			"Birthday": "1954-08-15",
			"favorite_dish": 19
		},
		{
			"id": 73,
			"first_name": "Merle",
			"last_name": "Sukbhans",
			"email": "msukbhans20@orangevalleycaa.org",
			"address": "574 Cherokee Terrace",
			"city": "Grand Rapids",
			"State": "MI",
			"phone_number": "616-189-2213",
			"Birthday": "1938-10-16",
			"favorite_dish": 13
		},
		{
			"id": 74,
			"first_name": "Giraldo",
			"last_name": "Algar",
			"email": "galgar21@kinetecoinc.com",
			"address": "17 Knutson Drive",
			"city": "Rochester",
			"State": "NY",
			"phone_number": "585-956-6225",
			"Birthday": "1901-09-14",
			"favorite_dish": 1
		},
		{
			"id": 75,
			"first_name": "Bevvy",
			"last_name": "Harrowsmith",
			"email": "bharrowsmith22@red30design.com",
			"address": "33 Crescent Oaks Lane",
			"city": "San Antonio",
			"State": "TX",
			"phone_number": "210-572-0107",
			"Birthday": "1954-09-24",
			"favorite_dish": 6
		},
		{
			"id": 76,
			"first_name": "Dyanna",
			"last_name": "Fulger",
			"email": "dfulger23@red30design.com",
			"address": "15859 Kings Pass",
			"city": "Roanoke",
			"State": "VA",
			"phone_number": "540-320-0153",
			"Birthday": "1926-12-06",
			"favorite_dish": 16
		},
		{
			"id": 77,
			"first_name": "Viola",
			"last_name": "McLarnon",
			"email": "vmclarnon24@orangevalleycaa.org",
			"address": "16 Hanover Street",
			"city": "Charlotte",
			"State": "NC",
			"phone_number": "704-789-2133",
			"Birthday": "1933-04-20",
			"favorite_dish": 13
		},
		{
			"id": 78,
			"first_name": "Dorella",
			"last_name": "Linbohm",
			"email": "dlinbohm25@rouxacademy.org",
			"address": "531 Mccormick Street",
			"city": "Stamford",
			"State": "CT",
			"phone_number": "203-835-7673",
			"Birthday": "1935-05-29",
			"favorite_dish": 4
		},
		{
			"id": 79,
			"first_name": "Winslow",
			"last_name": "Klass",
			"email": "wklass26@kinetecoinc.com",
			"address": "7 Green Road",
			"city": "Shreveport",
			"State": "LA",
			"phone_number": "318-130-3322",
			"Birthday": "1972-04-12",
			"favorite_dish": 21
		},
		{
			"id": 80,
			"first_name": "Francisca",
			"last_name": "Cranmor",
			"email": "fcranmor27@wisdompets.com",
			"address": "2161 Holy Cross Terrace",
			"city": "Norfolk",
			"State": "VA",
			"phone_number": "757-141-3735",
			"Birthday": "1958-02-24",
			"favorite_dish": 5
		},
		{
			"id": 81,
			"first_name": "Gustave",
			"last_name": "Alphonso",
			"email": "galphonso28@wisdompets.com",
			"address": "4855 Messerschmidt Crossing",
			"city": "Las Vegas",
			"State": "NV",
			"phone_number": "702-709-0059",
			"Birthday": "1937-03-24",
			"favorite_dish": 8
		},
		{
			"id": 82,
			"first_name": "Jacquette",
			"last_name": "Spillard",
			"email": "jspillard29@red30design.com",
			"address": "168 Clemons Avenue",
			"city": "Tacoma",
			"State": "WA",
			"phone_number": "253-406-0669",
			"Birthday": "1989-03-04",
			"favorite_dish": 7
		},
		{
			"id": 83,
			"first_name": "Caril",
			"last_name": "Matejic",
			"email": "cmatejic2a@orangevalleycaa.org",
			"address": "7 Texas Hill",
			"city": "Grand Rapids",
			"State": "MI",
			"phone_number": "616-748-1299",
			"Birthday": "1918-06-17",
			"favorite_dish": 15
		},
		{
			"id": 84,
			"first_name": "Sianna",
			"last_name": "Drewell",
			"email": "sdrewell2b@kinetecoinc.com",
			"address": "62198 Bultman Park",
			"city": "Milwaukee",
			"State": "WI",
			"phone_number": "414-182-9923",
			"Birthday": "1917-10-19",
			"favorite_dish": 21
		},
		{
			"id": 85,
			"first_name": "Sonnie",
			"last_name": "MatticcI",
			"email": "smatticci2c@rouxacademy.org",
			"address": "2 Roxbury Avenue",
			"city": "Simi Valley",
			"State": "CA",
			"phone_number": "805-544-5902",
			"Birthday": "1996-05-09",
			"favorite_dish": 5
		},
		{
			"id": 86,
			"first_name": "Brandais",
			"last_name": "Jeannaud",
			"email": "bjeannaud2d@hplussport.com",
			"address": "19539 Melvin Place",
			"city": "Oklahoma city",
			"State": "OK",
			"phone_number": "405-272-0078",
			"Birthday": "1987-04-18",
			"favorite_dish": 8
		},
		{
			"id": 87,
			"first_name": "Junie",
			"last_name": "MacRury",
			"email": "jmacrury2e@wisdompets.com",
			"address": "2958 Maple Wood Road",
			"city": "Lake Charles",
			"State": "LA",
			"phone_number": "337-515-7385",
			"Birthday": "1963-12-25",
			"favorite_dish": 11
		},
		{
			"id": 88,
			"first_name": "Gus",
			"last_name": "Holyland",
			"email": "gholyland2f@red30design.com",
			"address": "62 8th Pass",
			"city": "Seattle",
			"State": "WA",
			"phone_number": "425-916-5021",
			"Birthday": "1966-08-02",
			"favorite_dish": 8
		},
		{
			"id": 89,
			"first_name": "Ab",
			"last_name": "Jurn",
			"email": "ajurn2g@samoca.org",
			"address": "11398 Norway Maple Place",
			"city": "Oakland",
			"State": "CA",
			"phone_number": "415-269-1567",
			"Birthday": "1997-01-18",
			"favorite_dish": 11
		},
		{
			"id": 90,
			"first_name": "Elmo",
			"last_name": "Ockland",
			"email": "eockland2h@landonhotel.com",
			"address": "38494 Mitchell Park",
			"city": "Washington",
			"State": "DC",
			"phone_number": "202-866-5269",
			"Birthday": "1943-09-08",
			"favorite_dish": 15
		},
		{
			"id": 91,
			"first_name": "Iver",
			"last_name": "Palke",
			"email": "ipalke2i@rouxacademy.org",
			"address": "25182 Roxbury Avenue",
			"city": "Philadelphia",
			"State": "PA",
			"phone_number": "215-247-9059",
			"Birthday": "1982-08-04",
			"favorite_dish": 15
		},
		{
			"id": 92,
			"first_name": "Asher",
			"last_name": "Tapley",
			"email": "atapley2j@kinetecoinc.com",
			"address": "720 Saint Paul Plaza",
			"city": "Hialeah",
			"State": "FL",
			"phone_number": "786-938-4977",
			"Birthday": "1959-08-05",
			"favorite_dish": 7
		},
		{
			"id": 93,
			"first_name": "Joel",
			"last_name": "Baignard",
			"email": "jbaignard2k@orangevalleycaa.org",
			"address": "8 High Crossing Court",
			"city": "Amarillo",
			"State": "TX",
			"phone_number": "806-995-6798",
			"Birthday": "1937-01-26",
			"favorite_dish": 13
		},
		{
			"id": 94,
			"first_name": "Curr",
			"last_name": "Fittall",
			"email": "cfittall2l@orangevalleycaa.org",
			"address": "530 Mallory Pass",
			"city": "Green Bay",
			"State": "WI",
			"phone_number": "920-248-2709",
			"Birthday": "1910-08-20",
			"favorite_dish": 18
		},
		{
			"id": 95,
			"first_name": "Lelah",
			"last_name": "Seathwright",
			"email": "lseathwright2m@samoca.org",
			"address": "2649 Bellgrove Way",
			"city": "Houston",
			"State": "TX",
			"phone_number": "713-248-4719",
			"Birthday": "1999-07-07",
			"favorite_dish": 8
		},
		{
			"id": 96,
			"first_name": "Melantha",
			"last_name": "Scowcroft",
			"email": "mscowcroft2n@kinetecoinc.com",
			"address": "23879 Reindahl Center",
			"city": "New York city",
			"State": "NY",
			"phone_number": "212-694-0087",
			"Birthday": "1900-04-12",
			"favorite_dish": 18
		},
		{
			"id": 97,
			"first_name": "Herb",
			"last_name": "McParland",
			"email": "hmcparland2o@rouxacademy.org",
			"address": "39 Algoma Park",
			"city": "Chicago",
			"State": "IL",
			"phone_number": "630-950-3309",
			"Birthday": "1916-12-25",
			"favorite_dish": 14
		},
		{
			"id": 98,
			"first_name": "Clem",
			"last_name": "Durdy",
			"email": "cdurdy2p@hplussport.com",
			"address": "594 Bonner Point",
			"city": "Des Moines",
			"State": "IA",
			"phone_number": "515-680-5018",
			"Birthday": "1988-03-10",
			"favorite_dish": 16
		},
		{
			"id": 99,
			"first_name": "Kala",
			"last_name": "Simonian",
			"email": "ksimonian2q@landonhotel.com",
			"address": "95 Waywood Street",
			"city": "Huntington",
			"State": "WV",
			"phone_number": "304-681-5208",
			"Birthday": "1947-11-30",
			"favorite_dish": 5
		},
		{
			"id": 100,
			"first_name": "Blythe",
			"last_name": "Leggan",
			"email": "bleggan2r@rouxacademy.org",
			"address": "1622 Golf Course Hill",
			"city": "Montgomery",
			"State": "AL",
			"phone_number": "334-770-7364",
			"Birthday": "1996-06-11",
			"favorite_dish": 5
		}
	]
const db = require('../models/_index')
const Customer = db.Customer

try {
  db.sequelize.transaction(async (transaction) => {
      await Customer.bulkCreate(customers[0], { fields: ['id', 'first_name', 'last_name', 'email', 'address', 'city', 'phone_number', 'favorite_dish'], transaction }).then(() => {
        
      }).catch(err => { // SequelizeValidationError
        throw (err)
      })
    })
} catch (error) {

  console.log(error)
}
