version: "3.0"

services:

  db:
    image: postgres:latest
    container_name: schitts-cafe-db
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      POSTGRES_DB: schitts_cafe
    volumes:
       - pg_data:/var/lib/postgresql/data
    ports:
      - 9001:5432
    networks:
      -  schitts-cafe

  api:
    build: ./api
    container_name: schitts-cafe-api
    command: ["gunicorn", "-w", "8", "--threads=8", "--worker-class=gthread", "-b", "0.0.0.0:80", "run:app", "--log-level", "debug", "--reload", "--timeout", "320"]
    volumes:
      - .:/app
    ports:
      - 5000:80
    depends_on:
      - db
    restart: always
    networks:
      - schitts-cafe

  ui:
    container_name: schitts-cafe-ui
    build: ./ui
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 8080:80
    restart: always
    networks:
      - schitts-cafe

networks:
  schitts-cafe:
volumes:
  redis-data:
  pg_data:
