version: '3'

services:
  cariback:
    build: .
    restart: always
    container_name: cariback
    ports:
      - '33333:33333'
      - '33334:33334'
    depends_on:
      - carimongo
    environment:
      CARIB__ACCEPTED_CORS_ORIGINS: http://localhost:3000
      CARIB__MG_HOST: carimongo
      CARIB__MG_PORT: 27017
      CARIB__MG_DATABASE: cariboudb
      CARIB__MG_USER: DB_USER_TO_MOVE_INTO_ENV_FILE
      CARIB__MG_PASSWORD: DB_PASSWORD_TO_MOVE_INTO_ENV_FILE

  carimongo:
    image: mongo:latest
    container_name: carimongo
    restart: always
    volumes:
      - ./init/mongo/:/docker-entrypoint-initdb.d/
      - ./.docker/mongo/data/db/:/data/db/
      - ./.docker/mongo/data/log/:/var/log/mongodb/
    environment:
      MONGO_INITDB_DATABASE: cariboudb
      MONGO_INITDB_ROOT_USERNAME: DB_USER_TO_MOVE_INTO_ENV_FILE
      MONGO_INITDB_ROOT_PASSWORD: DB_PASSWORD_TO_MOVE_INTO_ENV_FILE
    ports:
      - '27017:27017'
