swagger: "2.0"
info:
  description: "Robot Oldoporto"
  version: "1.0.0"
  title: "La Poutine Mtl"
  termsOfService: ""
  contact:
    email: "jshn.singh1@gmail.com"
  license:
    name: "MIT OpenSource"
    url: "https://opensource.org/licenses/MIT"
host: "lapoutinemtl.com"
basePath: "/Oldoporto"
paths:
  /temperature:
    post:
      tags:
      - "temperature regulator"
      summary: "keep things at a specific temperature in a pot"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
