name: "Docker Linting"

on:
  push:
  pull_request:

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    name: "Hadolint"
    steps:
      - uses: actions/checkout@v2
      - uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: ./**/Dockerfile
