name: "Linting"

on:
  push:
  pull_request:

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ./botney-trap/Dockerfile
